import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Anton } from "next/font/google";
import "./globals.css";
import { AnimatePresence } from "motion/react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const anton = Anton({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-anton",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AnimatePresence>
        <body
          className={`${geistSans.variable} ${anton.variable} ${inter.variable} ${geistMono.variable} antialiased`}
        >
          {children}
        </body>
      </AnimatePresence>
    </html>
  );
}
